### ISSUE TITLE
Test failure on CI

### ISSUE THREAD

**Issue by ashander** [ashander/ftprime#18]
eg
```
    def check_tables(args):
        nodes = args.node_table()
        assert(nodes.num_rows == args.num_nodes)
        edgesets = args.edgeset_table()
        # check edgesets are in order and all parents are recorded
>       node_times = nodes.time
E       AttributeError: 'NodeTable' object has no attribute 'time'

tests/test_merge_records_with_wf.py:11: AttributeError
```

**Comment by petrelharp** [comment]
```
>>> import msprime
>>> node = msprime.NodeTable()
>>> node.time
array([], dtype=float64)
>>> print(msprime.__version__)
0.4.1.dev356+ng85413c9
```

One commit before the one I said above, but this hasn't changed.

**Comment by ashander** [comment]
OK, this works for me too on msprime (0658998) but it's unclear why or how it's not working in CI b/c the`environment.yml` is trying to check out the same commit. :angry: 

PS hard to understand these version strings. I don't think they're supposed to be repeatable across compilations, but not sure. in any case, the code below is from the same hash (I've run make just before the commands below)

```
 $ git log |head -5
commit 06589980d050982390b35f527bb38af9bafd5721
Merge: 85413c9 3d58746
Author: Jerome Kelleher <jk@well.ox.ac.uk>
Date:   Wed Apr 12 18:09:19 2017 +0100

(msprime-dev) jaime@shuksan:~/lib/msprime$ ((0658998...)) 
 $ python
Python 3.6.0 | packaged by conda-forge | (default, Feb  9 2017, 14:36:55) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
>>> node = msprime.NodeTable()
>>> node.time
array([], dtype=float64)
>>> print(msprime.__version__)
0.4.1.dev360+ng0658998
```

**Comment by ashander** [comment]
Ok, so can reproduce failure in another env, which is py35. So still unsure, but maybe a py35 vs py36 (as above) issue.

**Comment by ashander** [comment]
The underlying issue was my local envs and CI both did not have numpy

**Comment by ashander** [comment]
Filed https://github.com/jeromekelleher/msprime/issues/189 about this. Seems there should be warning on builiding `msprime` in an environment without numpy

**Comment by petrelharp** [comment]
There is - I forget where, but I think just after `make ext3`.
