### ISSUE TITLE
Deal with overlapping generations

### ISSUE THREAD

**Issue by ashander** [ashander/ftprime#19]
in RecombCollector non-overlapping is assumed at least in one place https://github.com/ashander/ftprime/blob/master/ftprime/recomb_collector.py#L65

**Comment by petrelharp** [comment]
I think the right thing to do is to write a new class based on RecombCollector, as it assumes many things - possibly also constant pop size?

**Comment by ashander** [comment]
closed, at least for now by #22 and some earlier commits
